import type { Metadata } from "next";
import "./globals.css";
import DarkModeProvider from "@/provider/DarkModeProvider";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Code Snippet Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DarkModeProvider>
        <body
          className={'dark:bg-black bg-gray-100 min-h-screen'}
        >
          <Header />
          {children}
        </body>
      </DarkModeProvider>
    </html>
  );
}
